name: .deb build orchestrator

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  source-only:
    permissions:
      id-token: write
      contents: read
      attestations: write
    uses: ./.github/workflows/deb-src.yml
    with:
      runs-on: ubuntu-24.04
    secrets:
      GPG_SECRET_SUBKEYS: ${{ secrets.GPG_SECRET_SUBKEYS }}
      GPG_SIGNING_SUBKEY_FINGERPRINT: ${{ secrets.GPG_SIGNING_SUBKEY_FINGERPRINT }}
  buildd:
    needs: source-only
    permissions:
      id-token: write
      contents: read
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        stack:
          - { runs-on: "ubuntu-24.04",     machine-arch: "amd64", build-arch: "amd64",   host-arch: "amd64" }
        dist:
          - { name: debian, version: unstable }
        exclude:
          - stack: { runs-on: "ubuntu-24.04",     machine-arch: "amd64", build-arch: "amd64",   host-arch: "ppc64el" }
            dist: { name: ubuntu, version: questing }
            # cross-build broken, package conflicts
          - stack: { runs-on: "ubuntu-24.04",     machine-arch: "amd64", build-arch: "amd64",   host-arch: "ppc64el" }
            dist: { name: ubuntu, version: plucky   }
            # cross-build broken, broken packages
        # # If someone asks for ubuntu ppc64el packages, these can be reenabled:
        # include:
        #   - stack: { runs-on: "ubuntu-24.04",     machine-arch: "amd64", build-arch: "ppc64el", host-arch: "ppc64el" }
        #     dist: { name: ubuntu, version: questing }
        #   - stack: { runs-on: "ubuntu-24.04",     machine-arch: "amd64", build-arch: "ppc64el", host-arch: "ppc64el" }
        #     dist: { name: ubuntu, version: plucky   }
    uses: ./.github/workflows/deb-buildd.yml
    with:
      deb-src-artifact-id: ${{ needs.source-only.outputs.deb-src-artifact-id }}
      runs-on: ${{ matrix.stack.runs-on }}
      machine-arch: ${{ matrix.stack.machine-arch }}
      build-arch: ${{ matrix.stack.build-arch }}
      host-arch: ${{ matrix.stack.host-arch }}
      dist-name: ${{ matrix.dist.name }}
      dist-version: ${{ matrix.dist.version }}
    secrets:
      GPG_SECRET_SUBKEYS: ${{ secrets.GPG_SECRET_SUBKEYS }}
      GPG_SIGNING_SUBKEY_FINGERPRINT: ${{ secrets.GPG_SIGNING_SUBKEY_FINGERPRINT }}
